#version: '3.8'
#services:
#  dynamodb-local:
#   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
#   image: "amazon/dynamodb-local:latest"
#   container_name: dynamodb-local
#   ports:
#     - "8000:8000"
#   volumes:
#      - "./docker/dynamodb:/home/dynamodblocal/data"
#    working_dir: /home/dynamodblocal

version: '3.1'

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566-4583:4566-4583"
    environment:
      - SERVICES=s3,dynamodb,sqs
#            - SERVICES=s3,lambda,sqs,apigateway
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
#      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"