server:
  port: 8082
  servlet:
    context-path: /balance-api
  error:
    include-message: always
    include-binding-errors: always

security:
  jwt:
    token:
      secret-key: signature_key

aws:
  #aws global configurations
  key: localstack
  secret: localstack
  region: us-east-1

  sqs:
    endpointUrl: http://localhost:4566