server:
  port: 8081
  servlet:
    context-path: /financial-api
  error:
    include-message: always
    include-binding-errors: always

security:
  jwt:
    token:
      secret-key: signature_key

aws:
  #aws global configurations
  key: localstack
  secret: localstack
  region: us-east-1

  #dynamodb configurations
  dynamodb:
    region: us-east-1
    endpointUrl: http://localhost:4566


